create table music(
id NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
danceability number(11,5),
energy number(11,5),
valence number(11,5),
popularity number(11,5), 
loudness number(11,5),
year number(11),
name varchar2(255),
artist varchar2(255)
);
