create table users(
id NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE,
f_name varchar2(50),
l_name varchar2(50),
r_date DATE default sysdate,
pass varchar2(50)
);

create table manage_users(
id number(10),
o_username varchar2(50),
n_username varchar2(50),
l_in_playlist date 
);

create table music(
id NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
danceability number(4,3),
energy number(4,3),
valence number(4,3),
popularity number(4,3), 
loudness number(4,3),
year number(4),
name varchar2(255),
artist varchar2(255)
);

create table top_music (
id number(10),
listen_count number(10)
);

create table users_music(
users_id number(10),
music_id number(10)
);


