# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuenCloud' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuenCloud
  pod 'IQKeyboardManager'
  pod 'SnapKit'
  pod 'SVProgressHUD'
  pod 'SDWebImage' 
  pod 'SwiftPhoneNumberFormatter' 
  pod 'BEMCheckBox'
  pod 'Kingfisher' 

end
